name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x, 17.x]
        redis-version: [6]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: ${{ matrix.redis-version }}
    - run: sudo systemctl start mysql.service
    - run: sudo mysql -e 'DROP DATABASE IF EXISTS events254_test;' -proot
    - run: sudo mysql -e 'CREATE DATABASE events254_test;' -proot
    - run: cp .env.example .env
    - run: npm ci
    - run: echo "Linting 👀"
    - run: npm run lint
    - run: echo "Testing 🚀"
    - run: npm test
    