name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 6
      - name: Start Mysql Server
        run: sudo systemctl start mysql.service
      - name: Create Database
        run: |
          sudo mysql -e 'DROP DATABASE IF EXISTS events254_test;' -proot
          sudo mysql -e 'CREATE DATABASE events254_test;' -proot
          sudo mysql -e 'ALTER USER "root"@"localhost" IDENTIFIED WITH mysql_native_password BY "root";' -proot
          cp .env.example .env
      - name: Install dependencies
        run: npm ci
      - name: Linting 👀
        run: npm run lint
      - name: Testing 🚀
        run: npm test
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production
      url: https://api.events254.co.ke
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
      - name: Run the deployment command
        run: |
          ssh stanley@64.225.23.199 "sh deploy.sh git@github.com:Events254/events254 /var/www/api.events254.co.ke/"
          ssh stanley@64.225.23.199 "pm2 restart ecosystem.config.js"
